import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import fs from 'node:fs';
import {analyzeRequirements} from '../lib/analysis.ts';
import {permissionFor,requireAdmin,permittedTaskUpdate} from '../lib/permissions.ts';
import {readProject,writeProject,PROJECT_KEY} from '../lib/project-data.ts';
import {readTimeline,changeTimeline,saveStoredTimeline,readStoredTimeline,TIMELINE_KEY} from '../lib/timeline.ts';
import {readSheets} from '../lib/workbook.ts';
import {syntheticBook} from './synthetic-fixture.mjs';
import {strToU8,zipSync} from 'fflate';
function gantt(){const b=readSheets(syntheticBook()),s=b.sheets[0];b.files['xl/workbook.xml']=strToU8(new TextDecoder().decode(b.files['xl/workbook.xml']).replace('name="How to use"','name="Gantt"'));const row=(i,a)=>'<row r="'+i+'">'+a.map((v,n)=>'<c r="'+String.fromCharCode(65+n)+i+'" t="inlineStr"><is><t>'+v+'</t></is></c>').join('')+'</row>';b.files[s.path]=strToU8('<worksheet><sheetData>'+row(7,['ID','Week','Workstream','Task','Lead','Support','Start','End','Status','%','Depends on','Notes'])+row(8,['A1','','Synthetic','First','Lead','','46294','46301','Planned','0','',''])+'</sheetData></worksheet>');return zipSync(b.files);}
class Bucket{objects=new Map();etag(b){return createHash('sha256').update(b).digest('hex')}async get(k){const b=this.objects.get(k);return b?{etag:this.etag(b),text:async()=>new TextDecoder().decode(b),arrayBuffer:async()=>new Uint8Array(b).buffer}:null;}async put(k,b,opts){b=typeof b==='string'?strToU8(b):b;const before=this.objects.get(k);if(opts?.onlyIf?.etagMatches&&(!before||this.etag(before)!==opts.onlyIf.etagMatches)||opts?.onlyIf?.etagDoesNotMatch==='*'&&before)return null;this.objects.set(k,b);return {etag:this.etag(b)};}}
const sources=()=>[{set:'icvsp',data:{records:[{values:{ID:'FR-01',Requirement:'Hazard reports use Ed25519 digital signatures for sender authentication and device identity before accepting message integrity.',Status:'Planned','Verification method':'Test','Verification level':'Integration',Evidence:''}},{values:{ID:'FR-02',Requirement:'A camera detects potholes locally.',Status:'Planned',Area:'Road'}}],sheets:[]}},{set:'security',data:{records:[{values:{ID:'FR-SEC-01',Requirement:'Device identity and sender authentication use Ed25519 digital signatures to protect hazard reports and message integrity.','Existing V-Cycle link':'FR-01',Status:'Planned'}},{values:{ID:'FR-SEC-02',Requirement:'A camera detects potholes locally.',Status:'Planned',Area:'Road'}}],sheets:[]}}];
test('analysis uses explicit IDs, separates suggestions, grounds evidence, and invalidates stale review evidence',()=>{const p={reviews:[],relationships:[]};const a=analyzeRequirements(sources(),p);assert.equal(a.nodes.length,4);assert.ok(a.edges.some(e=>e.origin==='recorded'&&e.source==='security:FR-SEC-01'&&e.target==='icvsp:FR-01'));const suggested=a.edges.find(e=>e.origin==='suggested'&&e.source==='icvsp:FR-01');assert.ok(suggested);assert.notEqual(suggested.type,'Depends On');assert.equal(suggested.status,'Suggested');assert.ok(suggested.evidence.some(e=>e.text===sources()[0].data.records[0].values.Requirement));p.reviews.push({...suggested,status:'Confirmed'});assert.equal(analyzeRequirements(sources(),p).edges.find(e=>e.id===suggested.id).status,'Confirmed');const changed=sources();changed[0].data.records[0].values.Requirement+=' TLS secure transport is also required.';assert.equal(analyzeRequirements(changed,p).edges.find(e=>e.id===suggested.id).status,'Needs Review');assert.ok(a.edges.some(e=>e.type==='Duplicate / Overlapping'));assert.ok(a.issues.some(i=>i.kind==='No test cases'));});
test('planning review decisions persist, stale writers fail, and requirement objects remain untouched',async()=>{const b=new Bucket();b.objects.set('requirement',strToU8('untouched'));const p=await readProject(b);const d={...p.data,reviews:[{id:'real-review',status:'Rejected'}],teams:[{id:'team1',name:'User entered team',members:['Lead']}]};const result=await writeProject(b,p.version,d);assert.equal(result.receipt.verified,true);assert.equal(result.receipt.key,PROJECT_KEY);assert.deepEqual((await readProject(b)).data,d);await assert.rejects(()=>writeProject(b,null,d),/changed/);assert.equal(new TextDecoder().decode(b.objects.get('requirement')),'untouched');});
test('anonymous/member/admin permissions are enforced and names alone never grant authority',()=>{const admin=permissionFor({email:'owner@example.test'},'owner@example.test'),member=permissionFor({email:'member@example.test'},'owner@example.test'),visitor=permissionFor(null,'owner@example.test');assert.equal(admin.canManage,true);assert.throws(()=>requireAdmin(member));assert.throws(()=>requireAdmin(visitor));const task={values:{Lead:'Lead'}};assert.throws(()=>permittedTaskUpdate(member,task,{op:'edit',progress:50},[]));const members=[{email:'member@example.test',shortName:'Lead'}];assert.doesNotThrow(()=>permittedTaskUpdate(member,task,{op:'edit',values:{Status:'In Progress'},progress:50},members));for(const a of [{op:'add'},{op:'edit',start:'2026-10-10'},{op:'edit',values:{Lead:'other'}},{op:'edit',extra:{team:'other'}},{op:'edit',links:[]}])assert.throws(()=>permittedTaskUpdate(member,task,a,members));});
test('new tasks and metadata persist to the same workbook; original tasks, sheets and IDs remain',async()=>{const b=new Bucket();b.objects.set(TIMELINE_KEY,gantt());const before=await readStoredTimeline(b);const result=await saveStoredTimeline(b,{op:'add',id:'A2',values:{ID:'A2',Task:'User-created task',Lead:'Lead',Status:'Not Started','Depends on':'A1'},start:'2026-10-15',end:'2026-10-20',progress:0,extra:{team:'team1',priority:'High',parent:'A1',description:'Actual entered description',deliverables:'Actual entered deliverable'},version:before.etag});assert.equal(result.receipt.verified,true);const after=await readStoredTimeline(b),task=after.data.tasks.find(t=>t.values.ID==='A2');assert.equal(task.extra.parent,'A1');assert.equal(task.progress,0);assert.deepEqual(task.dependencies,['A1']);assert.deepEqual(after.data.tasks.find(t=>t.values.ID==='A1'),before.data.tasks[0]);assert.equal(after.data.sheets.length,before.data.sheets.length);assert.throws(()=>changeTimeline(after.bytes,{op:'add',values:{ID:'A2',Task:'duplicate'}}),/unique/);assert.throws(()=>changeTimeline(after.bytes,{op:'edit',id:'A1',extra:{parent:'A2'}}),/cycle/);});
test('adding a task to the actual schedule preserves all original tasks and styles',{skip:!process.env.ICVSP_GANTT_TEST_WORKBOOK},()=>{const bytes=new Uint8Array(fs.readFileSync(process.env.ICVSP_GANTT_TEST_WORKBOOK)),before=readTimeline(bytes),changed=readTimeline(changeTimeline(bytes,{op:'add',id:'SYNTHETIC-QA',values:{ID:'SYNTHETIC-QA',Task:'Explicit isolated QA fixture task',Lead:'Malak',Status:'Not Started'},start:'2026-10-22',end:'2026-10-23',progress:0,extra:{parent:'C1'}}));assert.equal(changed.tasks.length,68);assert.equal(changed.tasks.find(t=>t.values.ID==='SYNTHETIC-QA').start,'2026-10-22');for(const t of before.tasks)assert.deepEqual(changed.tasks.find(n=>n.values.ID===t.values.ID),t);assert.deepEqual(changed.files['xl/styles.xml'],before.files['xl/styles.xml']);});

test('technical concepts use word boundaries and review comments flag only real referenced IDs',()=>{const data=sources();data[0].data.records[0].values.Requirement='The system performs plausibility checks on event timestamps and report age.';data[1].data.records[0].values.Requirement='Reject replayed messages with a freshness window and Message ID.';assert.ok(!analyzeRequirements(data,{reviews:[],relationships:[]}).edges.some(e=>e.origin==='suggested'&&e.source==='icvsp:FR-01'&&e.explanation.includes('bluetooth')));data[0].data.records[0].values['Review Comment']='A cloud-only decision would conflict with FR-02.';const a=analyzeRequirements(data,{reviews:[],relationships:[]});assert.ok(a.edges.some(e=>e.source==='icvsp:FR-01'&&e.target==='icvsp:FR-02'&&e.type==='Potential Conflict'&&e.status==='Suggested'));});

test('explicit abbreviated and ranged requirement IDs are expanded without inventing records',async()=>{const {requirementReferences}=await import('../lib/traceability.ts');assert.deepEqual(requirementReferences('FR-06/08/11 depend on NFR-10').sort(),['FR-06','FR-08','FR-11','NFR-10']);assert.deepEqual(requirementReferences('FR-SEC-05..08').sort(),['FR-SEC-05','FR-SEC-06','FR-SEC-07','FR-SEC-08']);});

test('typed dependencies and support suggestions are grounded in exact existing review references',()=>{const data=sources();data[0].data.records[0].values['Review Comment']='Depends on FR-02. This remains to be reviewed.';const a=analyzeRequirements(data,{reviews:[],relationships:[]});const e=a.edges.find(e=>e.source==='icvsp:FR-01'&&e.target==='icvsp:FR-02'&&e.type==='Depends On');assert.equal(e.status,'Suggested');assert.ok(e.evidence.some(v=>v.field==='Review Comment'&&v.text===data[0].data.records[0].values['Review Comment']));data[0].data.records[0].values['Review Comment']='This capability supports FR-02.';assert.ok(analyzeRequirements(data,{reviews:[],relationships:[]}).edges.some(e=>e.type==='Supports'&&e.status==='Suggested'));});

 test('team tasks follow saved unique owner memberships without changing workbook metadata',async()=>{const {resolveTaskTeam,withTeamAssignments}=await import('../lib/team-assignment.ts');const teams=[{id:'ai',members:['Shahesta','Rana']},{id:'cyber',members:['Malak','Ahmed','Moaz']},{id:'mobile',members:['Mariam']}];const task={values:{Lead:'Malak'},extra:{}};assert.deepEqual(resolveTaskTeam(task,teams),{id:'cyber',origin:'Owner membership'});assert.equal(resolveTaskTeam({values:{Lead:'Mariam'},extra:{}},teams).id,'mobile');assert.equal(resolveTaskTeam({values:{Lead:'All 6'},extra:{}},teams).id,'');assert.equal(resolveTaskTeam(task,[...teams,{id:'shared',members:['Malak']}]).id,'');assert.equal(resolveTaskTeam({...task,extra:{team:'ai'}},teams).id,'ai');const result=withTeamAssignments({tasks:[task]},teams);assert.equal(result.tasks[0].teamAssignment.id,'cyber');assert.deepEqual(task.extra,{});assert.deepEqual(result.tasks[0].extra,{});});
