// Synthetic data only. Never embed the user's workbook in this public repository.
import {zipSync,strToU8} from 'fflate';
export function syntheticBook(){
 const fields=['ID','Type','Area','Requirement','Rationale','Source','Acceptance criterion','Priority','Verification method','Verification level','Status','Evidence','Owner (WP)','Jira key','Review','Review Comment'];
 const names=['How to use','V diagram','Summary','V-Plan','Stakeholder needs','Requirements','Traceability','Test cases'];
 const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
 const row=(n,v)=>'<row r="'+n+'" ht="70" customHeight="1">'+v.map((x,i)=>'<c r="'+String.fromCharCode(65+i)+n+'" s="0" t="inlineStr"><is><t>'+esc(x)+'</t></is></c>').join('')+'</row>';
 const values=Array.from({length:37},(_,i)=>{const v=Object.fromEntries(fields.map(k=>[k,'']));v.ID=(i<23?'FR-':'NFR-')+String(i<23?i+1:i-22).padStart(2,'0');v.Type=i<23?'FR':'NFR';v.Requirement='Synthetic requirement '+(i+1);v.Area='Synthetic test area';v.Priority='Must';v.Status='Planned';return v});
 const data={};data['[Content_Types].xml']=strToU8('<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/></Types>');
 data['xl/workbook.xml']=strToU8('<workbook xmlns="'+ns+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+names.map((name,i)=>'<sheet name="'+name+'" sheetId="'+(i+1)+'" r:id="rId'+(i+1)+'"/>').join('')+'</sheets><calcPr calcId="1"/></workbook>');
 data['xl/_rels/workbook.xml.rels']=strToU8('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+names.map((_,i)=>'<Relationship Id="rId'+(i+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+(i+1)+'.xml"/>').join('')+'</Relationships>');
 for(let i=0;i<names.length;i++){let content=row(1,['Synthetic fixture']);if(i===5)content=row(1,fields)+values.map((v,j)=>row(j+2,fields.map(k=>v[k]))).join('');if(i===2)content='<row r="4"><c r="B4"><f>COUNTIF(Requirements!$K$2:$K$38,&quot;Planned&quot;)</f><v>37</v></c></row>';if(i===6)content=row(1,['Stakeholder need','Requirement','Requirement (short)','Architecture element','Software module','Unit verification','Integration verification','Software / system verification','Validation','Verification planned?','Verification executed?','Status (from Requirements)']);if(i===7)content=row(1,['Test ID','Name','File','V level','Covers requirements','Last result','Run date','Notes'])+Array.from({length:36},(_,j)=>row(j+2,['T-'+j,'Synthetic test','','Unit','','Pass','',''])).join('');data['xl/worksheets/sheet'+(i+1)+'.xml']=strToU8('<worksheet xmlns="'+ns+'"><dimension ref="A1:P38"/><sheetData>'+content+'</sheetData></worksheet>')}
 return zipSync(data);
}
