import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {zipSync,strToU8} from 'fflate';
import {readTimeline,changeTimeline,readStoredTimeline,saveStoredTimeline,importTimeline,TIMELINE_KEY,dateFromExcel,excelFromDate} from '../lib/timeline.ts';
import {readSheets} from '../lib/workbook.ts';
import {REQUIREMENT_SETS} from '../lib/requirement-sets.ts';
import {syntheticBook} from './synthetic-fixture.mjs';
import {traceFor,explicitlyContains} from '../lib/traceability.ts';
function fixture(){const b=readSheets(syntheticBook());const ws=b.sheets[0];const esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;');const row=(n,values)=>'<row r="'+n+'">'+values.map((v,i)=>'<c r="'+String.fromCharCode(65+i)+n+'" s="2" t="inlineStr"><is><t>'+esc(v)+'</t></is></c>').join('')+'</row>';b.files['xl/workbook.xml']=strToU8(new TextDecoder().decode(b.files['xl/workbook.xml']).replace('name="How to use"','name="Gantt"'));b.files[ws.path]=strToU8('<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+row(7,['ID','Week','Workstream','Task','Lead','Support (who helps, with what)','Start','End','Status','%','Depends on','Notes'])+row(8,['A1','W1','Synthetic','Synthetic task A','Lead','','46294','46299','In Progress','.25','','NFR-10'])+row(9,['A2','W1','Synthetic','Synthetic task B','Lead','','46301','46306','Planned','0','A1',''])+'</sheetData></worksheet>');return zipSync(b.files);}
class Bucket {objects=new Map([[TIMELINE_KEY,fixture()],[REQUIREMENT_SETS.icvsp.key,syntheticBook()],[REQUIREMENT_SETS.security.key,syntheticBook()]]);writes=[];etag(b){return createHash('sha256').update(b).digest('hex');}async get(key){const b=this.objects.get(key);return b?{etag:this.etag(b),arrayBuffer:async()=>new Uint8Array(b).buffer}:null;}async put(key,bytes,opts){const old=this.objects.get(key);if(opts?.onlyIf?.etagDoesNotMatch==='*'&&old)return null;if(opts?.onlyIf?.etagMatches&&(!old||this.etag(old)!==opts.onlyIf.etagMatches))return null;this.objects.set(key,new Uint8Array(bytes));this.writes.push(key);return {etag:this.etag(bytes)};}}
test('timeline date/progress/dependency edits persist to one workbook with requirement isolation',async()=>{const bucket=new Bucket(),untouched=Object.fromEntries(Object.values(REQUIREMENT_SETS).map(c=>[c.key,new Uint8Array(bucket.objects.get(c.key))]));let c=await readStoredTimeline(bucket);const action={op:'edit',id:'A2',values:{...c.data.tasks[1].values,Status:'In Progress','Depends on':'A1'},start:'2026-10-07',end:'2026-10-14',progress:35,links:[{set:'icvsp',id:'NFR-10'}],version:c.etag};const result=await saveStoredTimeline(bucket,action);assert.equal(result.receipt.verified,true);assert.equal(result.receipt.key,TIMELINE_KEY);c=await readStoredTimeline(bucket);const task=c.data.tasks.find(t=>t.values.ID==='A2');assert.equal(task.start,'2026-10-07');assert.equal(task.end,'2026-10-14');assert.equal(task.progress,35);assert.equal(task.duration,8);assert.deepEqual(task.dependencies,['A1']);assert.deepEqual(task.links,action.links);for(const [key,b] of Object.entries(untouched))assert.deepEqual(bucket.objects.get(key),b);await assert.rejects(()=>saveStoredTimeline(bucket,action),/changed/);assert.equal(bucket.writes.filter(k=>k===TIMELINE_KEY).length,1);assert.equal(readTimeline(c.bytes).sheets.length,8);});
test('timeline validation rejects cycles, self links, invalid dates/progress, renamed IDs and fabricated requirement links',async()=>{const bytes=fixture();for(const action of [{id:'A1',values:{'Depends on':'A2'}},{id:'A1',values:{'Depends on':'A1'}},{id:'A1',values:{'Depends on':'missing'}},{id:'A1',start:'2026-02-30'},{id:'A1',start:'2026-11-01',end:'2026-10-01'},{id:'A1',progress:101},{id:'A1',values:{ID:'new'}}])assert.throws(()=>changeTimeline(bytes,{...action,op:'edit'}));const bucket=new Bucket(),before=await readStoredTimeline(bucket);await assert.rejects(()=>saveStoredTimeline(bucket,{op:'edit',id:'A1',links:[{set:'icvsp',id:'MADE-UP'}],version:before.etag}),/existing active/);assert.equal(bucket.writes.length,0);const cleared=readTimeline(changeTimeline(bytes,{op:'edit',id:'A1',start:'',end:'',progress:null})).tasks[0];assert.equal(cleared.start,'');assert.equal(cleared.progress,null);assert.equal(cleared.duration,null);assert.equal(dateFromExcel('46294'),'2026-09-29');assert.equal(excelFromDate('2026-09-29'),'46294');});
test('actual Gantt workbook imports unchanged once and edits preserve original sheets, styles and task IDs',{skip:!process.env.ICVSP_GANTT_TEST_WORKBOOK},async()=>{const original=new Uint8Array(fs.readFileSync(process.env.ICVSP_GANTT_TEST_WORKBOOK));const before=readTimeline(original);assert.equal(before.tasks.length,67);assert.equal(before.sheets.length,5);assert.equal(before.columns.length,12);const bucket=new Bucket();bucket.objects.delete(TIMELINE_KEY);const imported=await importTimeline(bucket,original);assert.equal(imported.receipt.verified,true);assert.deepEqual(bucket.objects.get(TIMELINE_KEY),original);await assert.rejects(()=>importTimeline(bucket,original),/already imported/);const c=await readStoredTimeline(bucket);const source=c.data.tasks.find(t=>t.values.ID==='C1');const changed=await saveStoredTimeline(bucket,{op:'edit',id:'C1',values:{...source.values,Status:'Blocked','Depends on':'P6,P7,AI1'},start:'2026-10-07',end:'2026-10-20',progress:55,links:[{set:'icvsp',id:'NFR-10'}],version:c.etag});assert.equal(changed.tasks.find(t=>t.values.ID==='C1').progress,55);const after=readTimeline((await readStoredTimeline(bucket)).bytes);for(const t of before.tasks.filter(t=>t.values.ID!=='C1'))assert.deepEqual(after.tasks.find(n=>n.values.ID===t.values.ID),t);for(const name of ['Milestones','Lists']){const s=before.sheets.find(s=>s.name===name);assert.deepEqual(after.files[s.path],before.files[s.path]);}assert.deepEqual(after.files['xl/styles.xml'],before.files['xl/styles.xml']);assert.deepEqual(after.columns,before.columns);assert.deepEqual(after.tasks.map(t=>t.values.ID),before.tasks.map(t=>t.values.ID));const jira=after.sheets.find(s=>s.name==='Jira Backlog');const linked=jira.rows.find(r=>r.cells.C?.startsWith('C1:'));assert.equal(linked.cells.J,'Blocked');assert.equal(linked.cells.K,excelFromDate('2026-10-07'));});
test('traceability exposes explicit links and missing links without matching unrelated text',()=>{const data={records:[],sheets:[{name:'Traceability',rows:[{row:1,cells:{A:'Requirement',B:'Architecture element',C:'Software module'}},{row:2,cells:{A:'FR-01',B:'Camera',C:'Detection'}}]},{name:'Test cases',rows:[{row:1,cells:{A:'Test ID',B:'Covers requirements'}},{row:2,cells:{A:'T1',B:'FR-01, FR-02'}}]}]};const t=traceFor(data,{values:{ID:'FR-01','Review Comment':'See FR-02','Existing V-Cycle link':''}});assert.deepEqual(t.architecture,['Camera']);assert.deepEqual(t.modules,['Detection']);assert.equal(t.tests.length,1);assert.deepEqual(t.references,['FR-02']);assert.equal(t.needs.length,0);assert.equal(explicitlyContains('FR-SEC-05..08','FR-SEC-07'),true);assert.equal(explicitlyContains('FR-010','FR-01'),false);});
