import {withTeamAssignments} from '../../../lib/team-assignment';
import {projectUser} from '../../project-auth';
import {permissionFor,permittedTaskUpdate} from '../../../lib/permissions';
import {readProject} from '../../../lib/project-data';
import {env} from 'cloudflare:workers';
import {readStoredTimeline,saveStoredTimeline} from '../../../lib/timeline';
import {readStoredWorkbook,WorkbookMissing,WorkbookConflict} from '../../../lib/persistence';
const headers={'Cache-Control':'no-store, max-age=0','CDN-Cache-Control':'no-store','Cloudflare-CDN-Cache-Control':'no-store'};
async function requirements(){const sets=await Promise.all(['icvsp','security'].map(async set=>{try{const c=await readStoredWorkbook((env as any).BUCKET,set);return c.data.records.map((r:any)=>({set,id:r.values.ID,text:r.values.Requirement}));}catch(e){if(e instanceof WorkbookMissing)return [];throw e;}}));return sets.flat();}
export async function GET(request:Request){try{const c=await readStoredTimeline((env as any).BUCKET);if(new URL(request.url).searchParams.has('download'))return new Response(c.bytes,{headers:{...headers,'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="GNATT CHART.xlsx"'}});return Response.json({...withTeamAssignments(c.data,(await readProject((env as any).BUCKET)).data.teams),version:c.etag,storage:c.storage,requirements:await requirements(),readOnly:(env as any).WORKBOOK_READ_ONLY==='true'},{headers});}catch(e){if(e instanceof WorkbookMissing)return Response.json({missing:true,tasks:[]},{headers});return Response.json({error:(e as Error).message},{status:503,headers});}}
export async function POST(request:Request){try{if((env as any).WORKBOOK_READ_ONLY==='true')return Response.json({error:'Workbook writes are paused for deployment migration.'},{status:423,headers});const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'Invalid request origin.'},{status:403,headers});const raw=await request.text();if(raw.length>100000)throw Error('Task data exceeds the 100 KB limit.');const action=JSON.parse(raw),permission=permissionFor(await projectUser(request),(env as any).ADMIN_EMAILS??''),project=await readProject((env as any).BUCKET),current=await readStoredTimeline((env as any).BUCKET);const task=current.data.tasks.find((t:any)=>t.values.ID===action.id);permittedTaskUpdate(permission,task??{values:{}},action,project.data.members);if(action.extra?.team){const team=project.data.teams.find((t:any)=>t.id===action.extra.team);if(!team)throw Error('Select an existing team.');const lead=action.values?.Lead??task?.values.Lead;if(lead&&!['TBD','All 6'].includes(lead)&&!team.members.includes(lead))throw Error('The primary owner must belong to the assigned team.');}if(action.values?.Lead&&!['TBD','All 6',...current.data.team.map((m:any)=>m['Short name (used in Lead)']),...project.data.members.map((m:any)=>m.shortName)].includes(action.values.Lead))throw Error('Select an existing member.');const result=await saveStoredTimeline((env as any).BUCKET,action);return Response.json({...result,tasks:withTeamAssignments(result,project.data.teams).tasks,requirements:await requirements()},{headers});}catch(e){return Response.json({error:(e as Error).message},{status:e instanceof WorkbookConflict?409:/Admin sign-in|You may update|Members may update/.test((e as Error).message)?403:400,headers});}}
