import {withTeamAssignments} from '../../../lib/team-assignment';
import {env} from 'cloudflare:workers';
import {projectUser} from '../../project-auth';
import {permissionFor,requireAdmin} from '../../../lib/permissions';
import {readProject,writeProject} from '../../../lib/project-data';
import {readStoredWorkbook,WorkbookMissing,WorkbookConflict} from '../../../lib/persistence';
import {readStoredTimeline} from '../../../lib/timeline';
import {analyzeRequirements,RELATION_TYPES} from '../../../lib/analysis';
const headers={'Cache-Control':'no-store'};
async function payload(request:Request){const p=await readProject((env as any).BUCKET);const sources:any[]=[];for(const set of ['icvsp','security']){try{sources.push({set,data:(await readStoredWorkbook((env as any).BUCKET,set)).data});}catch(e){if(!(e instanceof WorkbookMissing))throw e;}}let timeline:any={tasks:[],team:[],milestones:[]},timelineVersion:string|null=null;try{const stored=await readStoredTimeline((env as any).BUCKET);timeline=stored.data;timelineVersion=stored.etag;}catch(e){if(!(e instanceof WorkbookMissing))throw e;}const permission=permissionFor(await projectUser(request),(env as any).ADMIN_EMAILS??'');return {...p,analysis:analyzeRequirements(sources,p.data,timeline.tasks),timeline:withTeamAssignments(timeline,p.data.teams),timelineVersion,permission};}
export async function GET(request:Request){try{const p=await payload(request);if(!p.permission.canManage)p.data={...p.data,members:p.data.members.map((m:any)=>({...m,email:m.email===p.permission.email?m.email:undefined,accountLinked:true}))};return Response.json(p,{headers});}catch(e){return Response.json({error:(e as Error).message},{status:503,headers});}}
export async function POST(request:Request){try{if((env as any).WORKBOOK_READ_ONLY==='true')throw Error('Writes are paused.');const permission=permissionFor(await projectUser(request),(env as any).ADMIN_EMAILS??'');requireAdmin(permission);if(request.headers.get('origin')!==new URL(request.url).origin)throw Error('Invalid request origin.');const raw=await request.text();if(raw.length>100000)throw Error('Planning request is too large.');const action=JSON.parse(raw),p=await payload(request);if(action.version!==p.version)throw new WorkbookConflict('Planning changed in another session. Refresh before retrying.');const data=structuredClone(p.data),at=new Date().toISOString();
if(action.op==='review'){const edge=p.analysis.edges.find((e:any)=>e.id===action.id);if(!edge||edge.origin==='recorded')throw Error('Choose a suggested or manually added relationship.');if(JSON.stringify(action.evidence)!==JSON.stringify(edge.evidence))throw new WorkbookConflict('Source evidence changed. Refresh analysis and review the current statements.');if(!['Confirmed','Rejected','Suggested','Needs Review'].includes(action.status)||!RELATION_TYPES.includes(action.type))throw Error('Invalid relationship review.');const record={...edge,status:action.status,type:action.type,explanation:String(action.explanation??edge.explanation).slice(0,10000),createdAt:edge.createdAt??at,reviewedAt:at,reviewedBy:permission.email};if(edge.origin==='manual')data.relationships=data.relationships.map((e:any)=>e.id===edge.id?record:e);else data.reviews=[...data.reviews.filter((e:any)=>e.id!==edge.id),record];}
else if(action.op==='relationship'){if(!p.analysis.nodes.some((n:any)=>n.key===action.source)||!p.analysis.nodes.some((n:any)=>n.key===action.target)||action.source===action.target||!RELATION_TYPES.includes(action.type))throw Error('Select two different existing requirements and a valid type.');data.relationships.push({id:crypto.randomUUID(),source:action.source,target:action.target,type:action.type,status:'Needs Review',confidence:'Human entered',explanation:String(action.explanation??'').slice(0,10000),evidence:[{field:'User-entered explanation',text:String(action.explanation??'')}],createdAt:at,createdBy:permission.email});}
else if(action.op==='team'){const name=String(action.name??'').trim();if(!name||name.length>120||data.teams.some((t:any)=>t.name===name&&t.id!==action.id))throw Error('Enter a unique team name.');const valid=new Set([...p.timeline.team.map((m:any)=>m['Short name (used in Lead)']),...data.members.map((m:any)=>m.shortName)]);if(!Array.isArray(action.members)||action.members.some((m:any)=>!valid.has(m)||['TBD','All 6'].includes(m)))throw Error('Select real member records.');if(action.id&&!data.teams.some((t:any)=>t.id===action.id))throw Error('Team no longer exists.');const next={id:action.id??crypto.randomUUID(),name,members:[...new Set(action.members)],createdAt:action.id?data.teams.find((t:any)=>t.id===action.id).createdAt:at,updatedAt:at};data.teams=action.id?data.teams.map((t:any)=>t.id===action.id?next:t):[...data.teams,next];}
else if(action.op==='member'){const shortName=String(action.shortName??'').trim(),name=String(action.name??'').trim(),email=String(action.email??'').trim().toLowerCase();if(!shortName||!name||!/^\S+@\S+\.\S+$/.test(email)||['TBD','All 6'].includes(shortName))throw Error('Enter a member name, source short name and valid account email.');if(data.members.some((m:any)=>m.email===email&&m.shortName!==shortName))throw Error('This email is linked to another member.');data.members=[...data.members.filter((m:any)=>m.shortName!==shortName),{shortName,name,email,createdAt:at}];}
else throw Error('Unsupported project action.');data.activity.unshift({op:action.op,id:action.id??action.name??action.shortName,at,actor:permission.email});data.activity=data.activity.slice(0,200);const saved=await writeProject((env as any).BUCKET,p.version,data);return Response.json({...await payload(request),receipt:saved.receipt},{headers});}catch(e){return Response.json({error:(e as Error).message},{status:e instanceof WorkbookConflict?409:/Admin sign-in/.test((e as Error).message)?403:400,headers});}}
