'use client';
import {traceFor} from '../lib/traceability';
export default function RequirementTraceability({data,record,set,onRequirement}:{data:any;record:any;set:'icvsp'|'security';onRequirement:(set:'icvsp'|'security',id:string)=>void}){
 const t=traceFor(data,record);const directStakeholder=record.values.Stakeholder||record.values.Stakeholders;
 function fields(values:any){return <dl>{Object.entries(values).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)||<span className="muted">Not recorded</span>}</dd></div>)}</dl>}
 return <section className="traceability"><div className="section-heading"><div><h4>Traceability</h4><p>Recorded workbook links for <strong>{record.values.ID}</strong></p></div><span className="badge">{t.trace.length} traceability rows</span></div><div className="trace-grid">
 <details open><summary>Stakeholders <b>{t.needs.length+(directStakeholder?1:0)}</b></summary>{directStakeholder&&<p>{directStakeholder}</p>}{t.needs.map((n:any,i:number)=><details className="trace-item" key={i}><summary>{n['Need ID']} · {n.Stakeholder||'Stakeholder unset'}</summary>{fields(n)}</details>)}{!t.needs.length&&!directStakeholder&&<p className="missing-link">No stakeholder link recorded.</p>}</details>
 <details open><summary>System components <b>{t.architecture.length}</b></summary>{t.architecture.map((v:any)=><p className="trace-token" key={v}>{v}</p>)}{!t.architecture.length&&<p className="missing-link">No component link recorded.</p>}</details>
 <details open><summary>Modules <b>{t.modules.length}</b></summary>{t.modules.map((v:any)=><p className="trace-token" key={v}>{v}</p>)}{!t.modules.length&&<p className="missing-link">No module link recorded.</p>}</details>
 <details open><summary>Related requirements <b>{t.references.length+t.crossLinks.length}</b></summary><div className="link-chips">{t.references.map(id=>{const found=data.records.some((r:any)=>r.values.ID===id);return <button key={id} className="button secondary" disabled={!found} onClick={()=>onRequirement(set,id)}>{id}{!found?' · Missing or deleted':''}</button>})}{t.crossLinks.map(id=><button key={'icvsp:'+id} className="button secondary" onClick={()=>onRequirement('icvsp',id)}>{id} · ICVSP</button>)}</div>{!t.references.length&&!t.crossLinks.length&&<p className="missing-link">No related requirement IDs recorded.</p>}{t.references.length>0&&<small>References from the recorded related fields or review comments.</small>}</details>
 <details open className="full"><summary>Test cases <b>{t.tests.length}</b></summary>{t.tests.map((test:any,i:number)=><details className="trace-item" key={i}><summary><span>{test['Test ID']} · {test.Name||test.Scenario||'Test case'}</span><span className="badge">{test['Last result']||test.Status||'Result unset'}</span></summary>{fields(test)}</details>)}{!t.tests.length&&<p className="missing-link">No test case explicitly covers this ID.</p>}</details>
 </div><details className="trace-raw"><summary>All recorded traceability fields</summary>{t.trace.length?t.trace.map((v:any,i:number)=><div className="relation" key={i}>{fields(v)}</div>):<p className="missing-link">No Traceability row exists for this requirement.</p>}</details>{t.security.length>0&&<details className="trace-raw"><summary>Security goals, threats and targets ({t.security.length})</summary>{t.security.map((l:any,i:number)=><details className="trace-item" key={i}><summary>{l.name} · {l.values['Goal ID']||l.values['Threat ID']||l.values['Target ID']||'Recorded link'}</summary>{fields(l.values)}</details>)}</details>}<p className="trace-note">Missing links are shown for review. Displaying them does not change Excel or create relationships.</p></section>;
}
