import {traceFor,requirementReferences} from './traceability.ts';
export const RELATION_TYPES=['Depends On','Supports','Refines','Implements','Related To','Potential Conflict','Duplicate / Overlapping','Verified By / Tested By'];
const concepts=[['identity','device identity','sender identity','device registry','sender authentication','unique identity','device id'],['integrity','digital signature','ed25519','message integrity','digitally signed','signature verification'],['transport','tls','secure transport','encrypted communication'],['replay','replay','duplicate message','expired message','message id','timestamp'],['local warning','local alert','local warning','offline warning'],['hazard detection','pothole detection','detect potholes','pothole detector'],['firmware','secure boot','firmware','flash encryption'],['privacy','personal data','privacy','data minimization'],['bluetooth','bluetooth','ble'],['keys','key management','private key','public key'],['trust','corroboration','trust score','consensus'],['latency','latency','response time']];
const key=(set:string,id:string)=>set+':'+id;
const normalize=(s:any)=>String(s??'').toLowerCase().replace(/\s+/g,' ').trim();
export function analyzeRequirements(sources:any[],project:any,tasks:any[]=[]){
 const nodes=sources.flatMap(({set,data}:any)=>data.records.map((record:any)=>{const trace=traceFor(data,record),values=record.values;const text=normalize([values.Requirement,values.Rationale,values['Acceptance criterion'],values['Acceptance criteria']].filter(Boolean).join(' '));return {key:key(set,values.ID),set,id:values.ID,values,trace,text,concepts:concepts.filter(([, ...phrases])=>phrases.some(p=>new RegExp('(^|[^a-z0-9])'+p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'($|[^a-z0-9])').test(text))).map(([c])=>c)};}));
 const map=new Map(nodes.map((n:any)=>[n.key,n])),edges:any[]=[],missing:any[]=[];
 function add(source:string,target:string,type:string,explanation:string,evidence:any,origin:string,confidence='High'){if(source===target)return;const id=origin+':'+source+'>'+target+':'+type;if(edges.some(e=>e.id===id))return;const old=project.reviews.find((r:any)=>r.id===id);edges.push({id,type,explanation,confidence,status:origin==='recorded'?'Recorded':old?.status??'Suggested',...old,evidence,origin,source,target,...(old&&JSON.stringify(old.evidence)!==JSON.stringify(evidence)?{status:'Needs Review',explanation:explanation+' Source evidence changed since the last review.'}:{})});}
 for(const n of nodes){for(const [field,v] of Object.entries(n.values)){if(!/related|link|review comment|depends/i.test(field))continue;for(const candidate of nodes){if(candidate.key===n.key)continue;if(candidate.set!==n.set&&!/existing v-cycle|icvsp|review|related|depends/i.test(field))continue;if(requirementReferences(v).includes(candidate.id))add(n.key,candidate.key,/depends/i.test(field)?'Depends On':'Related To','Explicit ID reference recorded in '+field,[{requirement:n.id,field,text:String(v)}],'recorded');}for(const id of requirementReferences(v))if(id!==n.id&&!nodes.some((c:any)=>c.id===id))missing.push({key:n.key,kind:'Missing reference',detail:field+': '+id});}}
 for(const n of nodes){const comment=String(n.values['Review Comment']??'');if(!/\b(?:conflict|inconsistency|inconsistent|contradict)|cannot reach/i.test(comment))continue;for(const id of requirementReferences(comment)){const candidate=nodes.find((c:any)=>c.set===n.set&&c.id===id&&c.key!==n.key);if(candidate)add(n.key,candidate.key,'Potential Conflict','The existing review comment flags a possible constraint mismatch. Review exact scope and conditions; this is not a confirmed contradiction.',[{requirement:n.id,field:'Review Comment',text:comment},{requirement:n.id,field:'Requirement',text:n.values.Requirement},{requirement:candidate.id,field:'Requirement',text:candidate.values.Requirement}],'suggested','Low');}}
 for(const n of nodes){const comment=String(n.values['Review Comment']??'');for(const m of comment.matchAll(/\b(depends? on|supports?)\s+([^.!?]+)/gi))for(const id of requirementReferences(m[2])){const target=nodes.find((c:any)=>c.set===n.set&&c.id===id&&c.key!==n.key);if(target)add(n.key,target.key,/depend/i.test(m[1])?'Depends On':'Supports','This relationship is expressed in the existing review comment; confirm its scope before accepting it.',[{requirement:n.id,field:'Review Comment',text:comment},{requirement:n.id,field:'Requirement',text:n.values.Requirement},{requirement:target.id,field:'Requirement',text:target.values.Requirement}],'suggested','Medium');}for(const m of comment.matchAll(/\b((?:FR|NFR)(?:-SEC)?-\d+(?:\/\d+)*)\s+depends?\s+on\s+it\b/gi))for(const id of requirementReferences(m[1])){const source=nodes.find((c:any)=>c.set===n.set&&c.id===id&&c.key!==n.key);if(source)add(source.key,n.key,'Depends On','The review of '+n.id+' explicitly states these requirements depend on it; human confirmation is required.',[{requirement:n.id,field:'Review Comment',text:comment},{requirement:source.id,field:'Requirement',text:source.values.Requirement},{requirement:n.id,field:'Requirement',text:n.values.Requirement}],'suggested','Medium');}}
 for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j];const common=a.concepts.filter((c:string)=>b.concepts.includes(c));const same=normalize(a.values.Requirement)&&normalize(a.values.Requirement)===normalize(b.values.Requirement);const words=(n:any)=>new Set(n.text.match(/[a-z][a-z0-9-]{4,}/g)??[]);const wa=words(a),wb=words(b),shared=[...wa].filter(w=>wb.has(w));const similarity=shared.length/Math.max(1,new Set([...wa,...wb]).size);let type='',why='',confidence='Medium';if(same||similarity>.68&&shared.length>=12){type='Duplicate / Overlapping';why=same?'Identical requirement statements.':'Substantial shared wording; check whether scopes or acceptance criteria differ.';confidence=same?'High':'Medium';}else if(common.length>=2&&shared.length>=3){type='Related To';why='Shared specific technical concepts: '+common.join(', ')+'. This does not establish a dependency.';}if(!type)continue;const prohibited=/\b(?:must not|shall not|prohibit|forbidden)\b/.test(a.text)!==/\b(?:must not|shall not|prohibit|forbidden)\b/.test(b.text);if(!same&&common.length>=2&&prohibited){type='Potential Conflict';why='Shared technical scope with a prohibition in only one statement. Review exact scope before deciding whether constraints conflict.';confidence='Low';}add(a.key,b.key,type,why,[...[a,b].flatMap((n:any)=>['Requirement','Rationale','Acceptance criterion','Acceptance criteria'].filter(f=>n.values[f]).map(field=>({requirement:n.id,field,text:n.values[field]}))),{field:'Shared technical concepts',text:common.join(', ')}],'suggested',confidence);}
 for(const r of project.relationships??[]){if(map.has(r.source)&&map.has(r.target))edges.push({...r,origin:'manual'});else missing.push({key:r.source,kind:'Missing reference',detail:'Stored relationship '+r.id+' targets a missing/deleted requirement.'});}
 const issues:any[]=[...missing];for(const n of nodes){for(const field of ['Requirement','Status',...(['Source','Area','Owner (WP)','Owner'].filter(f=>f in n.values)),...(['Verification method','Verification level','Acceptance criterion'].filter(f=>f in n.values))])if(!String(n.values[field]??'').trim())issues.push({key:n.key,kind:'Missing field',detail:field+' is unset.'});const vm=n.values['Verification method']||n.values.Verification;if(vm&&!n.trace.tests.length)issues.push({key:n.key,kind:'No test cases',detail:'Verification is recorded but no test case explicitly covers this ID.'});const evidenceField=Object.keys(n.values).find(f=>/^evidence(?:\s*\/\s*notes)?$/i.test(f));const evidence=evidenceField?n.values[evidenceField]:null;if(vm&&(evidenceField&&!evidence||'Verification level' in n.values&&!n.values['Verification level']))issues.push({key:n.key,kind:'Incomplete verification',detail:'An existing evidence or verification-level field is unset; existing fields are unchanged.'});else if(vm&&evidence&&/\bplanned\b/i.test(evidence)&&/planned/i.test(n.values.Status))issues.push({key:n.key,kind:'Incomplete verification',detail:'Evidence / notes describe planned verification; review executed-test evidence when available.'});if(!tasks.some((t:any)=>t.links?.some((l:any)=>key(l.set,l.id)===n.key)||[t.values.Task,t.values.Notes].some(v=>new RegExp('(^|[^A-Za-z0-9-])'+n.id+'($|[^A-Za-z0-9-])').test(v??''))))issues.push({key:n.key,kind:'No implementation task',detail:'No explicit task link or exact ID reference found; review whether one is needed.'});if(!edges.some(e=>e.status!=='Rejected'&&(e.source===n.key||e.target===n.key)))issues.push({key:n.key,kind:'Isolated',detail:'No identified requirement relationships. Isolation is not automatically an error.'});}
 const verificationLinks=nodes.flatMap((n:any)=>n.trace.tests.map((t:any)=>({source:n.key,testId:t['Test ID'],set:n.set,type:'Verified By / Tested By',status:'Recorded',test:t})));return {nodes,edges,issues,verificationLinks};
}
