import {zipSync,strFromU8,strToU8} from 'fflate';
import {readSheets} from './workbook.ts';
import {WorkbookConflict,WorkbookMissing,readStoredWorkbook} from './persistence.ts';
import {requirementSet} from './requirement-sets.ts';

export const TIMELINE_KEY='workbook/GNATT CHART.xlsx';
export const TIMELINE_IMPORT_SHA256='73261674755e89ba5c99b879286aace6beae0e1f6a0b3879cb8a0963fcb85a56';
const META='customXml/icvsp-timeline.xml';
const DAY=86400000,epoch=Date.UTC(1899,11,30);
const esc=(v:any)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function dateFromExcel(v:any){if(v===''||v==null)return '';const n=Number(v);return Number.isFinite(n)&&n>0&&n<2958466?new Date(epoch+Math.floor(n)*DAY).toISOString().slice(0,10):'';}
export function excelFromDate(v:string){if(!v)return '';if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)throw Error('Enter a valid date.');return String(Math.round((Date.parse(v+'T00:00:00Z')-epoch)/DAY));}
const deps=(value:string)=>[...new Set(value.split(/[,;\s]+/).filter(Boolean))];
export function readTimeline(bytes:Uint8Array){
 const b=readSheets(bytes),sheet=b.sheets.find((s:any)=>s.name==='Gantt');if(!sheet)throw Error('The existing Gantt sheet is missing.');
 const header=sheet.rows.find((r:any)=>r.cells.A==='ID'&&r.cells.D==='Task');if(!header)throw Error('Gantt task headers are missing.');
 const columns=Object.entries(header.cells).filter(([,name])=>!!name).map(([letter,name])=>({letter,name:String(name)}));
 for(const field of ['ID','Task','Start','End','Status','%','Depends on'])if(!columns.some(c=>c.name===field))throw Error('Gantt field missing: '+field);
 let metadata:any={links:{},activity:[]};if(b.files[META]){const m=strFromU8(b.files[META]).match(/<data>([\s\S]*?)<\/data>/)?.[1];if(m)metadata=JSON.parse(m.replaceAll('&quot;','"').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&amp;','&'));}
 const tasks=sheet.rows.filter((r:any)=>r.row>header.row&&r.cells.A&&r.cells.D).map((r:any)=>{
  const values=Object.fromEntries(columns.map(c=>[c.name,r.cells[c.letter]??'']));const start=dateFromExcel(values.Start),end=dateFromExcel(values.End);const p=values['%']===''?null:Number(values['%'])*100;
  return {row:r.row,values,extra:metadata.extra?.[values.ID]??{},start,end,progress:p===null||!Number.isFinite(p)?null:Math.round(p*1000)/1000,duration:start&&end?Math.round((Date.parse(end)-Date.parse(start))/DAY)+1:null,dependencies:deps(values['Depends on']),links:metadata.links?.[values.ID]??[]};
 });
 if(new Set(tasks.map((t:any)=>t.values.ID)).size!==tasks.length)throw Error('Duplicate task IDs in the Gantt source.');
 const table=(name:string)=>{const s=b.sheets.find((s:any)=>s.name===name);if(!s)return [];return s.rows.slice(1).map((r:any)=>Object.fromEntries(Object.entries(s.rows[0].cells).map(([c,k])=>[String(k),r.cells[c]??''])));};
 return {...b,sheet,columns,tasks,metadata,data:{columns,tasks,activity:metadata.activity??[],sheets:b.sheets.map((s:any)=>({name:s.name})),team:table('Team'),milestones:table('Milestones'),lists:table('Lists'),calendar:sheet.rows.find((r:any)=>r.row===3)?.cells??{},filename:'GNATT CHART.xlsx'}};
}
export function changeTimeline(bytes:Uint8Array,action:any){
 const b=readTimeline(bytes);if(action.op==='add'){const id=String(action.values?.ID??'').trim();if(!/^[A-Za-z0-9][A-Za-z0-9_-]{0,79}$/.test(id)||b.tasks.some((t:any)=>t.values.ID===id))throw Error('Enter a unique task ID using letters, numbers, hyphen or underscore.');const row=Math.max(...b.sheet.rows.map((r:any)=>r.row))+1;const values=Object.fromEntries(b.columns.map(c=>[c.name,c.name==='ID'?id:c.name==='Task'?String(action.values?.Task??'New task'):'']));const template=b.tasks.at(-1);const original=template?b.sheet.xml.match(new RegExp('<row\\b[^>]*r="'+template.row+'"[^>]*>[\\s\\S]*?</row>'))?.[0]:undefined;let xml=original?original.replace(/\br="([A-Z]*)(\d+)"/g,(_m:string,col:string)=>'r="'+col+row+'"').replace(/<f([^>]*)>([\s\S]*?)<\/f>/g,(_m:string,attrs:string,f:string)=>'<f'+attrs+'>'+f.replace(new RegExp('([A-Z]+)(\\$?)'+template!.row+'(?![0-9])','g'),(_x:string,c:string,a:string)=>c+a+row)+'</f>'): '<row r="'+row+'">'+b.columns.map(c=>'<c r="'+c.letter+row+'" t="inlineStr"><is><t>'+esc(values[c.name])+'</t></is></c>').join('')+'</row>';if(original)xml=xml.replace(/<c\b[^>]*>[\s\S]*?<\/c>/g,(cell:string)=>{const col=cell.match(/r="([A-Z]+)\d+"/)?.[1],field=b.columns.find(c=>c.letter===col);if(!field||field.name==='Week')return cell;const style=cell.match(/s="\d+"/)?.[0]??'';return '<c r="'+col+row+'" '+style+' t="inlineStr"><is><t>'+esc(values[field.name])+'</t></is></c>';});b.files[b.sheet.path]=strToU8(b.sheet.xml.replace('</sheetData>',xml+'</sheetData>'));return changeTimeline(zipSync(b.files),{...action,op:'edit',id,values:{...action.values,ID:id}});}const task=b.tasks.find((t:any)=>t.values.ID===action.id);if(!task)throw Error('Task no longer exists. Refresh before editing.');
 if(action.op!=='edit')throw Error('Unsupported timeline action.');
 const values:Record<string,string>={...task.values};for(const c of b.columns){if(c.name==='ID'||c.name==='Week')continue;if(action.values?.[c.name]!==undefined)values[c.name]=String(action.values[c.name]);}
 if(action.values?.ID&&action.values.ID!==task.values.ID)throw Error('Task IDs are preserved to protect dependencies.');
 if(!values.Task.trim())throw Error('Task name is required.');
 if(Object.values(values).some(v=>v.length>32767||/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(v)))throw Error('Invalid Excel field value.');
 const start=action.start===undefined?task.start:String(action.start),end=action.end===undefined?task.end:String(action.end);
 values.Start=excelFromDate(start);values.End=excelFromDate(end);if(start&&end&&end<start)throw Error('End date must be on or after the start date.');
 if(action.progress!==undefined){if(action.progress===null||action.progress==='')values['%']='';else{const p=Number(action.progress);if(!Number.isFinite(p)||p<0||p>100)throw Error('Progress must be between 0 and 100 percent.');values['%']=String(p/100);}}
 const dependencyIds=deps(values['Depends on']);const ids=new Set(b.tasks.map((t:any)=>t.values.ID));for(const id of dependencyIds)if(!ids.has(id)||id===action.id)throw Error('Dependencies must refer to other existing task IDs.');
 const graph=new Map(b.tasks.map((t:any)=>[t.values.ID,t.values.ID===action.id?dependencyIds:t.dependencies]));const visiting=new Set<string>(),visited=new Set<string>();
 function visit(id:string){if(visiting.has(id))throw Error('Dependency links cannot form a cycle.');if(visited.has(id))return;visiting.add(id);for(const next of graph.get(id)??[])visit(next);visiting.delete(id);visited.add(id);}visit(action.id);
 if(action.links!==undefined){if(!Array.isArray(action.links)||action.links.length>100)throw Error('Invalid requirement links.');const seen=new Set();b.metadata.links??={};b.metadata.links[action.id]=action.links.map((l:any)=>{if(!['icvsp','security'].includes(l.set))throw Error('Choose a requirement set for each link.');const set=requirementSet(l.set);if(typeof l.id!=='string'||!l.id||l.id.length>120||seen.has(set+':'+l.id))throw Error('Invalid or duplicate requirement link.');seen.add(set+':'+l.id);return {set,id:l.id};});}
 if(action.extra!==undefined){const extra=action.extra;if(!extra||typeof extra!=='object'||Array.isArray(extra))throw Error('Invalid task planning fields.');for(const field of ['description','team','priority','parent','deliverables'])if(typeof (extra[field]??'')!=='string'||String(extra[field]??'').length>10000)throw Error('Invalid task planning value.');if(extra.parent===action.id||extra.parent&&!ids.has(extra.parent))throw Error('Parent must be another existing task.');let parent=extra.parent;const seen=new Set([action.id]);while(parent){if(seen.has(parent))throw Error('Parent tasks cannot form a cycle.');seen.add(parent);parent=b.tasks.find((t:any)=>t.values.ID===parent)?.extra?.parent;}b.metadata.extra??={};b.metadata.extra[action.id]=Object.fromEntries(['description','team','priority','parent','deliverables'].map(k=>[k,extra[k]??'']));}
 const r=task.row;let xml=b.sheet.xml;const original=xml.match(new RegExp('<row\\b[^>]*r="'+r+'"[^>]*>[\\s\\S]*?</row>'))?.[0];if(!original)throw Error('Original task row is missing.');
 let updatedRow=original;
 for(const c of b.columns){const field=c.name;if(field==='ID'||field==='Week'||task.values[field]===values[field])continue;const ref=c.letter+r;const re=new RegExp('<c\\b[^>]*r="'+ref+'"[^>]*(?:/>|>[\\s\\S]*?</c>)');const cell=updatedRow.match(re)?.[0];const style=cell?.match(/\bs="\d+"/)?.[0]??'';const numeric=['Start','End','%'].includes(field);const next='<c r="'+ref+'" '+style+(numeric?'><v>'+values[field]+'</v>': ' t="inlineStr"><is><t xml:space="preserve">'+esc(values[field])+'</t></is>')+'</c>';updatedRow=cell?updatedRow.replace(re,()=>next):updatedRow.replace('</row>',next+'</row>');}
 // Refresh the existing Week and bar formula caches. Keep formulas, styles and layout intact.
 const week=values.Start?'W'+(Math.floor((Number(values.Start)-46293)/7)+1):'';
 updatedRow=updatedRow.replace(/<c\b[^>]*>[\s\S]*?<\/c>/g,(cell:string)=>{const ref=cell.match(/\br="([A-Z]+)\d+"/)?.[1];if(!cell.includes('<f')||!ref)return cell;let cached:string|undefined;if(ref==='B')cached=week;else{const serial=b.sheet.rows.find((x:any)=>x.row===6)?.cells[ref];if(serial)cached=values.Start&&values.End&&Number(serial)<=Number(values.End)&&Number(serial)+6>=Number(values.Start)?(['Completed','In Progress'].includes(values.Status)?'':' ')+(values.Lead||'TBD'):'';}return cached===undefined?cell:cacheString(cell,cached);});
 b.files[b.sheet.path]=strToU8(xml.replace(original,()=>updatedRow));
 // Derived Team/Jira cells retain their formulas and receive updated cached results.
 const nextTasks=b.tasks.map((t:any)=>t.values.ID===action.id?{...t,values}:t);
 const jira=b.sheets.find((s:any)=>s.name==='Jira Backlog');if(jira){let x=jira.xml;x=x.replace(/<c\b[^>]*>[\s\S]*?<\/c>/g,(cell:string)=>{const formula=cell.match(/<f[^>]*>([\s\S]*?)<\/f>/)?.[1];if(!formula)return cell;const id=formula.match(/MATCH\((?:&quot;|")([^"<]+?)(?:&quot;|")/ )?.[1];if(id!==action.id)return cell;const ref=formula.match(/'Gantt'!\$([DEGHIJK])\$/)?.[1];const field=({D:'Task',E:'Lead',G:'Start',H:'End',I:'Status',J:'%',K:'Depends on'} as any)[ref??''];if(!field)return cell;let v=values[field];if(cell.includes("'Team'!")||formula.includes("'Team'!")){const team=b.sheets.find((s:any)=>s.name==='Team');v=team?.rows.find((r:any)=>r.cells.A===values.Lead)?.cells.B??'';}else if(field==='Task')v=action.id+': '+v;return ['Start','End','%'].includes(field)?cacheNumber(cell,v):cacheString(cell,v);});b.files[jira.path]=strToU8(x);}
 const team=b.sheets.find((s:any)=>s.name==='Team');if(team){let x=team.xml;for(const row of team.rows.filter((r:any)=>r.row>1)){const led=nextTasks.filter((t:any)=>t.values.Lead===row.cells.A);for(const [letter,n] of [['D',led.length],['E',led.filter((t:any)=>t.values.Status==='Completed').length]] as const){const re=new RegExp('<c\\b[^>]*r="'+letter+row.row+'"[^>]*>[\\s\\S]*?</c>');x=x.replace(re,(cell:string)=>cell.includes('<f')?cacheNumber(cell,String(n)):cell);}}b.files[team.path]=strToU8(x);}
 b.metadata.activity.unshift({op:action.op,id:action.id,at:new Date().toISOString()});b.metadata.activity=b.metadata.activity.slice(0,100);b.files[META]=strToU8('<?xml version="1.0"?><timeline xmlns="urn:icvsp:timeline"><data>'+esc(JSON.stringify(b.metadata))+'</data></timeline>');
 let rel=strFromU8(b.files['xl/_rels/workbook.xml.rels']);if(!rel.includes('icvsp-timeline.xml'))rel=rel.replace('</Relationships>','<Relationship Id="rIdIcvspTimeline" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXml" Target="../customXml/icvsp-timeline.xml"/></Relationships>');b.files['xl/_rels/workbook.xml.rels']=strToU8(rel);
 let types=strFromU8(b.files['[Content_Types].xml']);if(!types.includes('/'+META))types=types.replace('</Types>','<Override PartName="/'+META+'" ContentType="application/xml"/></Types>');b.files['[Content_Types].xml']=strToU8(types);
 let wb=strFromU8(b.files['xl/workbook.xml']);wb=wb.replace(/<calcPr\b[^>]*\/?\s*>/,'<calcPr calcId="191029" fullCalcOnLoad="1" forceFullCalc="1"/>');b.files['xl/workbook.xml']=strToU8(wb);return zipSync(b.files);
}
function cacheString(cell:string,v:string){cell=cell.replace(/\st="[^"]*"/,'').replace(/^<c /,'<c t="str" ');return /<v[^>]*>/.test(cell)?cell.replace(/<v[^>]*>[\s\S]*?<\/v>/,'<v>'+esc(v)+'</v>'):cell.replace('</c>','<v>'+esc(v)+'</v></c>');}
function cacheNumber(cell:string,v:string){cell=cell.replace(/\st="[^"]*"/,'');return /<v[^>]*>/.test(cell)?cell.replace(/<v[^>]*>[\s\S]*?<\/v>/,'<v>'+v+'</v>'):cell.replace('</c>','<v>'+v+'</v></c>');}
async function hash(bytes:Uint8Array){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes).buffer)),b=>b.toString(16).padStart(2,'0')).join('');}
export async function readStoredTimeline(bucket:any){if(!bucket)throw Error('Timeline storage unavailable.');const o=await bucket.get(TIMELINE_KEY);if(!o)throw new WorkbookMissing('Import the supplied Gantt workbook once.');const bytes=new Uint8Array(await o.arrayBuffer());return {bytes,data:readTimeline(bytes).data,etag:o.etag,storage:{key:TIMELINE_KEY,etag:o.etag,sha256:await hash(bytes),bytes:bytes.length,readAt:new Date().toISOString()}};}
export async function importTimeline(bucket:any,bytes:Uint8Array){if(await hash(bytes)!==TIMELINE_IMPORT_SHA256)throw Error('Select the supplied GNATT CHART.xlsx workbook.');const b=readTimeline(bytes);if(b.tasks.length!==67||b.sheets.length!==5)throw Error('Unexpected Gantt source structure.');const saved=await bucket.put(TIMELINE_KEY,bytes,{onlyIf:{etagDoesNotMatch:'*'},httpMetadata:{contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}});if(!saved)throw new WorkbookConflict('The timeline is already imported. Existing data will not be replaced.');const c=await readStoredTimeline(bucket);if(c.etag!==saved.etag||c.storage.sha256!==TIMELINE_IMPORT_SHA256)throw Error('Timeline import verification failed.');return {...c.data,version:c.etag,storage:c.storage,receipt:{operation:'import',verified:true,...c.storage}};}
export async function saveStoredTimeline(bucket:any,action:any){if(action.op==='add')action={...action,id:String(action.values?.ID??'').trim()};const before=await readStoredTimeline(bucket);if(action.version!==before.etag)throw new WorkbookConflict('The timeline changed in another session. Refresh before saving; your draft is preserved.');
 if(action.links?.length){for(const set of ['icvsp','security']){const links=action.links.filter((l:any)=>l.set===set);if(!links.length)continue;const req=await readStoredWorkbook(bucket,set);if(links.some((l:any)=>!req.data.records.some((r:any)=>r.values.ID===l.id)))throw Error('Choose existing active requirements for task links.');}}
 const updated=changeTimeline(before.bytes,action);const expected=readTimeline(updated).tasks.find((t:any)=>t.values.ID===action.id);await bucket.put('workbook/backups/timeline/'+Date.now()+'-'+crypto.randomUUID()+'.xlsx',before.bytes);const saved=await bucket.put(TIMELINE_KEY,updated,{onlyIf:{etagMatches:before.etag},httpMetadata:{contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}});if(!saved)throw new WorkbookConflict('Another timeline edit was saved first. Refresh before retrying.');const c=await readStoredTimeline(bucket);if(c.etag!==saved.etag||c.bytes.length!==updated.length||c.bytes.some((v,i)=>v!==updated[i])||JSON.stringify(c.data.tasks.find((t:any)=>t.values.ID===action.id))!==JSON.stringify(expected))throw Error('Timeline save could not be verified. Refresh to inspect the live workbook.');return {...c.data,version:c.etag,storage:c.storage,receipt:{operation:action.op,id:action.id,verified:true,beforeEtag:before.etag,...c.storage}};}
